[package]
name = "lumen-curve"
version = "0.2.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
lumen-math = { git = "https://github.com/Tranduy1dol/lumen-math", version = "1.2.0"}
rand = "0.9.2"

[features]
test = []
